// src/app/layout.tsx

import './globals.css';
import { ReduxProvider } from './providers';
import RestoreRole from './RestoreRole';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <body>
        <ReduxProvider>
          <RestoreRole /> 
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}