import './globals.css';
import { Provider } from 'react-redux';
import { store } from '../redux/store';

function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <body>
        <Provider store={store}>
          {children}
        </Provider>
      </body>
    </html>
  );
}

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default RootLayout;
